version: '3.5'
networks:
  summariser:
    name: summariser
services:
  postgres:
    command:
    - postgres
    - -c
    - max_connections=150
    env_file:
    - ./.env
    build: ./postgres
    networks:
      summariser: null
    ports:
    - 5432:5432
    restart: always
    volumes:
    - /Users/christopher.chong/data/postgres:/var/lib/postgresql/data